approve_by_comment: true
approve_regex: '^(Approved|`^:\+1:`)'
reject_regex: '^(Rejected|`^:\-1:`)'
author_approval: required
reset_on_push: true
reset_on_reopened: true
reviewers:
    -
        name: admin
        required: 1
        members:
            - alan196